### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by devstsoy** [dddmisc/dddmisc#2]
```python
import asyncio
from d3m.domain import DomainCommand
from d3m.hc import HandlersCollection
from d3m.messagebus import Messagebus


class BaseDomainCommand(DomainCommand, domain="test"):
    pass


class Test(BaseDomainCommand):
    data: dict


hc = HandlersCollection()


@hc.register
async def test(cmd: Test):
    print(cmd.data)


async def main():
    mb = Messagebus()
    mb.include_collection(hc)
    await mb.run()
    await mb.handle_message(Test(data={"key": "value"}))
    await mb.stop()


if __name__ == '__main__':
    asyncio.run(main())

```
```
Traceback (most recent call last):
  File "ddd.py", line 27, in main
    await mb.handle_message(Test(data={"key": "value"}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/d3m/messagebus/messagebus.py", line 189, in handle_message
    return self._handle_command(message, dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/d3m/messagebus/messagebus.py", line 206, in _handle_command
    self._add_message(task, command)
  File ".venv/lib/python3.11/site-packages/d3m/messagebus/messagebus.py", line 242, in _add_message
    self._tasks[message] = task
    ~~~~~~~~~~~^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 451, in hash_func
    return hash(getter(self.__dict__))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

**Comment by vvorobyov** [comment]
fix in https://github.com/dddmisc/dddmisc/pull/8
